server:
  port: 8003
spring:
  application:
    name: cloud-provider-payment8003
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka,http://localhost:7001/eureka

