server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lihang.springcloud.entities
