server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7002/eureka
    fetch-registry: false